<?php
/**
 * Plugin Name: KB Native Customer Care Bridge
 * Description: API, website widget, R2 media and Firebase push bridge for the KB Movies native customer-care app.
 * Version: 1.0.0
 * Author: KSDigital Solutions
 * Requires PHP: 7.4
 */
if (!defined('ABSPATH')) exit;
define('KBCC_VERSION','1.0.0'); define('KBCC_URL',plugin_dir_url(__FILE__));
function kbcc_tables(){global $wpdb;return [$wpdb->prefix.'kbcc_conversations',$wpdb->prefix.'kbcc_messages',$wpdb->prefix.'kbcc_devices'];}
register_activation_hook(__FILE__,function(){global $wpdb;[$c,$m,$d]=kbcc_tables();$ch=$wpdb->get_charset_collate();require_once ABSPATH.'wp-admin/includes/upgrade.php';dbDelta("CREATE TABLE $c (id bigint unsigned NOT NULL AUTO_INCREMENT,public_id varchar(64) NOT NULL,user_id bigint unsigned NULL,guest_hash char(64) NULL,customer_name varchar(190) NOT NULL,agent_id bigint unsigned NOT NULL,status varchar(30) NOT NULL DEFAULT 'open',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY public_id(public_id),KEY agent_status(agent_id,status)) $ch;");dbDelta("CREATE TABLE $m (id bigint unsigned NOT NULL AUTO_INCREMENT,conversation_id bigint unsigned NOT NULL,sender_type varchar(20) NOT NULL,sender_id bigint unsigned NULL,message_type varchar(20) NOT NULL DEFAULT 'text',body text NULL,media_url text NULL,object_key varchar(500) NULL,mime_type varchar(100) NULL,created_at datetime NOT NULL,PRIMARY KEY(id),KEY conversation_id(conversation_id,id)) $ch;");dbDelta("CREATE TABLE $d (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,token varchar(255) NOT NULL,platform varchar(20) NOT NULL DEFAULT 'android',updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY token(token),KEY user_id(user_id)) $ch;");add_role('kbcc_agent','Customer Care Agent',['read'=>true,'kbcc_agent'=>true]);$a=get_role('administrator');if($a)$a->add_cap('kbcc_agent');});
function kbcc_now(){return current_time('mysql');} function kbcc_json($d,$s=200){return new WP_REST_Response($d,$s);} function kbcc_bearer(){return preg_match('/Bearer\s+(\S+)/i',$_SERVER['HTTP_AUTHORIZATION']??'',$m)?$m[1]:'';}
function kbcc_agent_id(){if(is_user_logged_in()&&current_user_can('kbcc_agent'))return get_current_user_id();$t=kbcc_bearer();if(!$t)return 0;$u=get_users(['meta_key'=>'kbcc_api_token_hash','meta_value'=>hash('sha256',$t),'number'=>1,'fields'=>'ids']);return $u?absint($u[0]):0;} function kbcc_agent_permission(){return kbcc_agent_id()>0;}
function kbcc_guest_hash(){if(is_user_logged_in())return '';$v=sanitize_text_field(wp_unslash($_COOKIE['kbcc_guest']??''));if(!preg_match('/^[a-f0-9]{64}$/',$v)){$v=bin2hex(random_bytes(32));setcookie('kbcc_guest',$v,['expires'=>time()+YEAR_IN_SECONDS,'path'=>'/','secure'=>is_ssl(),'httponly'=>true,'samesite'=>'Lax']);$_COOKIE['kbcc_guest']=$v;}return hash('sha256',$v.wp_salt('auth'));}
function kbcc_customer_access($x){return $x&&((is_user_logged_in()&&absint($x->user_id)===get_current_user_id())||(!$x->user_id&&hash_equals((string)$x->guest_hash,kbcc_guest_hash())));} function kbcc_rate($b,$max=50){$key='kbcc_'.md5($b.(is_user_logged_in()?get_current_user_id():kbcc_guest_hash()));$n=absint(get_transient($key));if($n>=$max)return false;set_transient($key,$n+1,MINUTE_IN_SECONDS);return true;}
function kbcc_agent_data($id){$u=get_userdata($id);return ['id'=>$id,'name'=>$u?$u->display_name:'Agent','avatar'=>get_avatar_url($id),'available'=>(bool)get_user_meta($id,'kbcc_available',true)];}
add_action('rest_api_init',function(){register_rest_route('kbcc/v1','/login',['methods'=>'POST','callback'=>'kbcc_login','permission_callback'=>'__return_true']);register_rest_route('kbcc/v1','/me',['methods'=>'GET','callback'=>fn()=>kbcc_json(kbcc_agent_data(kbcc_agent_id())),'permission_callback'=>'kbcc_agent_permission']);register_rest_route('kbcc/v1','/availability',['methods'=>'POST','callback'=>'kbcc_availability','permission_callback'=>'kbcc_agent_permission']);register_rest_route('kbcc/v1','/device',['methods'=>'POST','callback'=>'kbcc_device','permission_callback'=>'kbcc_agent_permission']);register_rest_route('kbcc/v1','/agents',['methods'=>'GET','callback'=>'kbcc_agents','permission_callback'=>'__return_true']);register_rest_route('kbcc/v1','/conversations',['methods'=>'GET','callback'=>'kbcc_conversations','permission_callback'=>'kbcc_agent_permission']);register_rest_route('kbcc/v1','/conversations/(?P<id>\d+)/messages',['methods'=>'GET','callback'=>'kbcc_messages','permission_callback'=>'kbcc_conversation_permission']);register_rest_route('kbcc/v1','/messages',['methods'=>'POST','callback'=>'kbcc_send','permission_callback'=>'__return_true']);register_rest_route('kbcc/v1','/media/presign',['methods'=>'POST','callback'=>'kbcc_presign','permission_callback'=>'__return_true']);register_rest_route('kbcc/v1','/customer/start',['methods'=>'POST','callback'=>'kbcc_customer_start','permission_callback'=>'__return_true']);});
function kbcc_login($r){if(!kbcc_rate('login',10))return kbcc_json(['message'=>'Too many attempts'],429);$u=wp_authenticate(sanitize_text_field($r['username']),(string)$r['password']);if(is_wp_error($u)||!user_can($u,'kbcc_agent'))return kbcc_json(['message'=>'Invalid customer-care login'],401);$t=bin2hex(random_bytes(32));update_user_meta($u->ID,'kbcc_api_token_hash',hash('sha256',$t));return kbcc_json(['token'=>$t,'agent'=>kbcc_agent_data($u->ID)]);}
function kbcc_availability($r){$id=kbcc_agent_id();update_user_meta($id,'kbcc_available',(bool)$r['available']?1:0);return kbcc_json(kbcc_agent_data($id));}
function kbcc_device($r){global $wpdb;[,, $d]=kbcc_tables();$t=sanitize_text_field($r['token']);if(!$t)return kbcc_json(['message'=>'Token required'],400);$wpdb->replace($d,['user_id'=>kbcc_agent_id(),'token'=>$t,'platform'=>'android','updated_at'=>kbcc_now()],['%d','%s','%s','%s']);return kbcc_json(['saved'=>true]);}
function kbcc_agents(){$u=get_users(['role__in'=>['kbcc_agent','administrator'],'meta_key'=>'kbcc_available','meta_value'=>'1']);return kbcc_json(array_map(fn($x)=>kbcc_agent_data($x->ID),$u));}
function kbcc_conversations(){global $wpdb;[$c,$m]=kbcc_tables();$rows=$wpdb->get_results($wpdb->prepare("SELECT c.*,(SELECT COALESCE(NULLIF(x.body,''),CONCAT('[',x.message_type,']')) FROM $m x WHERE x.conversation_id=c.id ORDER BY x.id DESC LIMIT 1) last_message,(SELECT COUNT(*) FROM $m x WHERE x.conversation_id=c.id AND x.sender_type='customer') unread FROM $c c WHERE c.agent_id=%d AND c.status!='closed' ORDER BY c.updated_at DESC LIMIT 100",kbcc_agent_id()),ARRAY_A);return kbcc_json($rows);}
function kbcc_conversation_permission($r){global $wpdb;[$c]=kbcc_tables();$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM $c WHERE id=%d",absint($r['id'])));$a=kbcc_agent_id();return ($a&&absint($x->agent_id)===$a)||kbcc_customer_access($x);}
function kbcc_messages($r){global $wpdb;[, $m]=kbcc_tables();$rows=$wpdb->get_results($wpdb->prepare("SELECT id,sender_type,message_type,body,media_url,created_at FROM $m WHERE conversation_id=%d AND id>%d ORDER BY id ASC LIMIT 200",absint($r['id']),absint($r['after'])),ARRAY_A);return kbcc_json(['messages'=>$rows,'next_after'=>$rows?absint(end($rows)['id']):absint($r['after'])]);}
function kbcc_customer_start($r){if(!kbcc_rate('start',10))return kbcc_json(['message'=>'Please wait'],429);global $wpdb;[$c]=kbcc_tables();$a=absint($r['agent_id']);if(!$a||!get_user_meta($a,'kbcc_available',true))return kbcc_json(['message'=>'Agent is unavailable'],409);$name=is_user_logged_in()?wp_get_current_user()->display_name:sanitize_text_field($r['name']);if(!$name)return kbcc_json(['message'=>'Name required'],400);$p=wp_generate_uuid4();$now=kbcc_now();$wpdb->insert($c,['public_id'=>$p,'user_id'=>get_current_user_id()?:null,'guest_hash'=>is_user_logged_in()?null:kbcc_guest_hash(),'customer_name'=>$name,'agent_id'=>$a,'status'=>'open','created_at'=>$now,'updated_at'=>$now],['%s','%d','%s','%s','%d','%s','%s','%s']);return kbcc_json(['id'=>$wpdb->insert_id,'public_id'=>$p,'agent'=>kbcc_agent_data($a)]);}
function kbcc_send($r){if(!kbcc_rate('send',60))return kbcc_json(['message'=>'Please wait'],429);global $wpdb;[$c,$m]=kbcc_tables();$cid=absint($r['conversation_id']);$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM $c WHERE id=%d",$cid));if(!$x)return kbcc_json(['message'=>'Conversation not found'],404);$a=kbcc_agent_id();$sender=($a&&absint($x->agent_id)===$a)?'agent':'customer';if($sender==='customer'&&!kbcc_customer_access($x))return kbcc_json(['message'=>'Forbidden'],403);$type=sanitize_key($r['type']?:'text');if(!in_array($type,['text','image','audio'],true))return kbcc_json(['message'=>'Invalid type'],400);$body=sanitize_textarea_field($r['body']);$now=kbcc_now();$wpdb->insert($m,['conversation_id'=>$cid,'sender_type'=>$sender,'sender_id'=>$a?:get_current_user_id(),'message_type'=>$type,'body'=>$body,'media_url'=>esc_url_raw($r['media_url']),'object_key'=>sanitize_text_field($r['object_key']),'mime_type'=>sanitize_mime_type($r['mime_type']),'created_at'=>$now],['%d','%s','%d','%s','%s','%s','%s','%s','%s']);$wpdb->update($c,['updated_at'=>$now],['id'=>$cid],['%s'],['%d']);$row=$wpdb->get_row($wpdb->prepare("SELECT id,sender_type,message_type,body,media_url,created_at FROM $m WHERE id=%d",$wpdb->insert_id),ARRAY_A);if($sender==='customer')kbcc_push_agent($x->agent_id,$x->customer_name,$type==='text'?$body:'New '.$type.' message',$cid);return kbcc_json($row,201);}
function kbcc_presign($r){global $wpdb;[$c]=kbcc_tables();$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM $c WHERE id=%d",absint($r['conversation_id'])));if(!$x)return kbcc_json(['message'=>'Conversation not found'],404);$a=kbcc_agent_id();if(!(($a&&absint($x->agent_id)===$a)||kbcc_customer_access($x)))return kbcc_json(['message'=>'Forbidden'],403);if(!function_exists('mkr2u_presign_put_url')||!function_exists('mkr2u_public_url'))return kbcc_json(['message'=>'R2 unavailable'],503);$kind=sanitize_key($r['kind']);$mime=sanitize_mime_type($r['mime_type']);$size=absint($r['size']);$allow=$kind==='image'?['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp']:['audio/mp4'=>'m4a','audio/mpeg'=>'mp3','audio/webm'=>'webm','audio/ogg'=>'ogg'];if(!isset($allow[$mime])||!$size||$size>($kind==='image'?8:20)*MB_IN_BYTES)return kbcc_json(['message'=>'Invalid media'],400);$key='native-support/'.gmdate('Y/m').'/'.$x->id.'/'.wp_generate_uuid4().'.'.$allow[$mime];$url=mkr2u_presign_put_url($key,900);if(is_wp_error($url))return kbcc_json(['message'=>$url->get_error_message()],500);return kbcc_json(['upload_url'=>$url,'public_url'=>mkr2u_public_url($key),'object_key'=>$key]);}
function kbcc_b64($v){return rtrim(strtr(base64_encode($v),'+/','-_'),'=');} function kbcc_fcm_access_token(){$s=(array)get_option('kbcc_fcm',[]);if(empty($s['client_email'])||empty($s['private_key']))return '';$n=time();$h=kbcc_b64(wp_json_encode(['alg'=>'RS256','typ'=>'JWT']));$c=kbcc_b64(wp_json_encode(['iss'=>$s['client_email'],'scope'=>'https://www.googleapis.com/auth/firebase.messaging','aud'=>'https://oauth2.googleapis.com/token','iat'=>$n,'exp'=>$n+3500]));if(!openssl_sign("$h.$c",$sig,$s['private_key'],OPENSSL_ALGO_SHA256))return '';$r=wp_remote_post('https://oauth2.googleapis.com/token',['timeout'=>15,'body'=>['grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>"$h.$c.".kbcc_b64($sig)]]);$j=json_decode(wp_remote_retrieve_body($r),true);return $j['access_token']??'';}
function kbcc_push_agent($agent,$name,$body,$cid){global $wpdb;[,, $d]=kbcc_tables();$tokens=$wpdb->get_col($wpdb->prepare("SELECT token FROM $d WHERE user_id=%d",$agent));$s=(array)get_option('kbcc_fcm',[]);$access=kbcc_fcm_access_token();if(!$access||empty($s['project_id']))return;foreach($tokens as $t)wp_remote_post('https://fcm.googleapis.com/v1/projects/'.rawurlencode($s['project_id']).'/messages:send',['timeout'=>10,'headers'=>['Authorization'=>'Bearer '.$access,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['message'=>['token'=>$t,'data'=>['title'=>$name,'body'=>wp_strip_all_tags($body),'conversation_id'=>(string)$cid],'android'=>['priority'=>'high']]])]);}
add_action('admin_menu',function(){add_options_page('Native Customer Care','Native Customer Care','manage_options','kbcc','kbcc_settings_page');});function kbcc_settings_page(){if(!current_user_can('manage_options'))return;$s=(array)get_option('kbcc_fcm',[]);if(isset($_POST['save'])&&check_admin_referer('kbcc_save')){$s=['project_id'=>sanitize_text_field($_POST['project_id']??''),'client_email'=>sanitize_email($_POST['client_email']??''),'private_key'=>trim(wp_unslash($_POST['private_key']??''))];update_option('kbcc_fcm',$s,false);echo '<div class="notice notice-success"><p>Settings saved.</p></div>';}?><div class="wrap"><h1>Native Customer Care</h1><form method="post"><?php wp_nonce_field('kbcc_save');?><table class="form-table"><tr><th>Firebase project ID</th><td><input class="regular-text" name="project_id" value="<?php echo esc_attr($s['project_id']??'');?>"></td></tr><tr><th>Service-account email</th><td><input class="regular-text" type="email" name="client_email" value="<?php echo esc_attr($s['client_email']??'');?>"></td></tr><tr><th>Private key</th><td><textarea class="large-text code" rows="8" name="private_key"><?php echo esc_textarea($s['private_key']??'');?></textarea><p>Keep this server-side. Never add it to GitHub or the Android app.</p></td></tr></table><button class="button button-primary" name="save" value="1">Save Settings</button></form></div><?php }
add_action('wp_enqueue_scripts',function(){if(is_admin())return;wp_enqueue_style('kbcc-widget',KBCC_URL.'assets/widget.css',[],KBCC_VERSION);wp_enqueue_script('kbcc-widget',KBCC_URL.'assets/widget.js',[],KBCC_VERSION,true);wp_localize_script('kbcc-widget','KBCC',['api'=>rest_url('kbcc/v1/'),'nonce'=>wp_create_nonce('wp_rest'),'loggedIn'=>is_user_logged_in(),'name'=>is_user_logged_in()?wp_get_current_user()->display_name:'']);});add_action('wp_footer',function(){if(is_admin())return;?><div id="kbcc-web"><button id="kbcc-open" aria-label="Open customer care">💬</button><section id="kbcc-panel" hidden><header><strong>KB Movies Support</strong><button id="kbcc-close">×</button></header><div id="kbcc-content"></div></section></div><?php },50);
